# Generated by Django 5.0.6 on 2024-07-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apisapp', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
