# Generated by Django 5.0.6 on 2024-08-03 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisapp', '0005_user_admission_no_user_billed_user_classteacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='email',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='name',
        ),
        migrations.AddField(
            model_name='messages',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(default='no messages', max_length=2000),
        ),
    ]
