# Generated by Django 5.0.6 on 2024-08-03 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisapp', '0006_remove_messages_email_remove_messages_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='no messages', max_length=2000)),
                ('time', models.TimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='messages',
            name='time',
        ),
        migrations.AddField(
            model_name='messages',
            name='email',
            field=models.EmailField(default='gideonushindi94@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='messages',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
