# Generated by Django 5.0.6 on 2024-08-03 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisapp', '0008_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='no message', max_length=2000)),
                ('time', models.TimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
