# Generated by Django 5.0.6 on 2024-08-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisapp', '0012_store_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(default='None', max_length=20)),
                ('time', models.TimeField(default='00:00')),
                ('cost', models.IntegerField(default=0)),
                ('seats', models.IntegerField(default=0)),
            ],
        ),
    ]
