# Generated by Django 5.0.6 on 2024-08-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisapp', '0013_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(default='john@example.com', max_length=254),
        ),
    ]
