# Generated by Django 5.0.6 on 2024-08-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisapp', '0014_store_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(default='County', max_length=40)),
                ('forest', models.CharField(default='forest_name', max_length=40)),
                ('area_square', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
