# Generated by Django 5.0.6 on 2024-09-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisapp', '0015_forest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=45)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('password', models.CharField(default='password', max_length=10)),
                ('personID', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
            ],
        ),
    ]
